### ISSUE TITLE
Home Assistant Custom Integration Changes

### ISSUE THREAD

**Issue by c3r63ru5** [realthk/asyncpioneer#23]
Hey,

spotted some error in ha logs after upgrading:
`ERROR (SyncWorker_2) [homeassistant.loader] The custom integration 'pioneer' does not have a valid version key (None) in the manifest file and was blocked from loading. See https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions for more details`

[https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions](https://developers.home-assistant.io/blog/2021/01/29/custom-integration-changes#versions)

manifest.json needs the "Version" key, so adding
`"version": "1.0",`
solves the issue, otherwise HA refuses to load the extension.

Cheers,
Sebastian

**Comment by realthk** [comment]
Yes, that's why it's [in the manifest.json](https://github.com/realthk/asyncpioneer/blob/master/manifest.json)

**Comment by c3r63ru5** [comment]
I could have pulled the latest instead of fixing my old version. Thanks!
